os: linux
dist: bionic
jobs:
  fast_finish: true
  include:
  - stage: test
    name: Lint helm chart
    script:
    - helm lint charts/marina/

  - stage: deploy
    name: Publish helm chart release
    script:
    - touch ./public/.nojekyll
    - charts/marina/add-repos.sh
    - helm package --dependency-update --destination ./public/charts charts/marina
    - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
    - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - helm repo index --url https://${TRAVIS_REPO_OWNER}.github.io/${TRAVIS_REPO_NAME}/charts ./public/charts
    deploy:
      provider: pages
      local_dir: public
      skip_cleanup: true
      # Generate a GitHub access token for public repositories
      # In your travis ci settings, set the token as a secret environment variable $GH_TOKEN
      token: "$GH_TOKEN"
      keep_history: true
      on:
        repo: romnn/marina
        tags: false
        branches:
          only:
            - master
before_script:
- curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
