apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marina.fullname" . }}-harbor-auth-config-json
type: Opaque
stringData:
  # see https://goharbor.io/docs/2.0.0/install-config/configure-user-settings-cli/ for reference
  auth.json: |
    {
        "auth_mode": "ldap_auth",
        "ldap_url": "{{ .Values.ldapmanager.ldap.protocol }}://{{ .Values.ldapmanager.ldap.host }}:{{ .Values.ldapmanager.ldap.port }}",
        "ldap_base_dn": {{ .Values.ldapmanager.ldap.baseDN | quote }},
        "ldap_search_dn": "cn={{ .Values.ldapmanager.ldap.readonly.user }},{{ .Values.ldapmanager.ldap.baseDN }}",
        "ldap_search_password": {{ .Values.ldapmanager.ldap.readonly.password | quote }},
        "ldap_uid": {{ .Values.ldapmanager.accountAttribute | quote }},
        "ldap_scope": 2,
        "ldap_filter": "objectclass=posixAccount",
        "ldap_group_base_dn": "ou={{ .Values.ldapmanager.groupsOU }},{{ .Values.ldapmanager.ldap.baseDN }}",
        "ldap_group_search_filter": "objectclass=posixGroup",
        "ldap_group_search_scope": 2,
        "ldap_group_attribute_name": "cn",
        "ldap_group_admin_dn": "cn={{ .Values.ldapmanager.defaultAdminGroup }},ou={{ .Values.ldapmanager.groupsOU }},{{ .Values.ldapmanager.ldap.baseDN }}",
        "ldap_group_membership_attribute": {{ .Values.ldapmanager.groupMembershipAttribute | quote }},
        "self_registration": false
    }
  password: {{ .Values.harbor.harborAdminPassword | quote }}
  host: http://{{ include "marina.fullname" . }}-harbor-core