apiVersion: v1
entries:
  marina:
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2020-09-01T00:00:08.672977598Z"
    dependencies:
    - condition: harbor.enabled
      name: harbor
      repository: '@harbor'
      version: '>=1.4.2'
    - condition: ldapmanager.enabled
      name: ldapmanager
      repository: '@ldapmanager'
      version: '>=0.0.18'
    description: Your own private docker and helm registry on bare-metal kubernetes.
    digest: cb503b1221a6331c3ac34ff3d566913c07b46a0cf88afa7faf526566b1f377c6
    icon: https://romnnn.github.io/marina/icons/icon_lg.jpg
    name: marina
    type: application
    urls:
    - https://romnnn.github.io/marina/charts/marina-0.0.8.tgz
    version: 0.0.8
generated: "2020-09-01T00:00:08.666684003Z"
