name: release
on:
  push:
    tags:
      - '*'

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint helm chart
        run: helm lint charts/marina/

      - run: |
          echo ::set-env name=REPO_USER::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}' ) 
          echo ::set-env name=REPO_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' ) 

      - name: Package helm chart
        run: |
          mkdir ./public
          touch ./public/.nojekyll
          charts/marina/add-repos.sh
          helm package --dependency-update --destination ./public/charts charts/marina
          helm repo index --url https://${REPO_USER}.github.io/${REPO_NAME}/charts ./public/charts

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
