name: release
on:
  push:
    tags:
      - '*'

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint helm chart
        run: helm lint charts/marina/

      - run: |
          echo "repo_user=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $1}' )" >> $GITHUB_ENV
          echo "repo_name=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}' )" >> $GITHUB_ENV

      - name: Package helm chart
        run: |
          touch ./public/.nojekyll
          charts/marina/add-repos.sh
          helm package --dependency-update --destination ./public/charts charts/marina
          helm repo index --url https://${{ env.repo_user }}.github.io/${{ env.repo_name }}/charts ./public/charts

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
